============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0
rootdir: /data/sandeep/leetcode-master/.verifaiws
collected 1 item

001_Two_Sum/test_001_Two_Sum.py F                                        [100%]

=================================== FAILURES ===================================
_________________________________ test_twoSum __________________________________

    def test_twoSum():
        s = Solution()
    
        nums = [2, 7, 11, 15]
        target = 9
        assert s.twoSum(nums, target) == [0, 1]
    
        nums = [3, 2, 4]
        target = 6
        assert s.twoSum(nums, target) == [1, 2]
    
        nums = [3, 3]
        target = 6
        assert s.twoSum(nums, target) == [0, 1]
    
        nums = [-1, 0, 1, 2, -1, -4]
        target = -1
>       assert s.twoSum(nums, target) == [0, 5]
E       assert [0, 1] == [0, 5]
E         At index 1 diff: 1 != 5
E         Use -v to get more diff

001_Two_Sum/test_001_Two_Sum.py:23: AssertionError
=========================== short test summary info ============================
FAILED 001_Two_Sum/test_001_Two_Sum.py::test_twoSum - assert [0, 1] == [0, 5]
============================== 1 failed in 0.01s ===============================
