============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0
rootdir: /data/sandeep/leetcode-master/.verifaiws
collected 0 items / 1 error

==================================== ERRORS ====================================
______ ERROR collecting 253_Meeting_Rooms_II/test_253_Meeting_Rooms_II.py ______
ImportError while importing test module '/data/sandeep/leetcode-master/.verifaiws/253_Meeting_Rooms_II/test_253_Meeting_Rooms_II.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
253_Meeting_Rooms_II/test_253_Meeting_Rooms_II.py:2: in <module>
    from solution import Interval, Solution
E   ImportError: cannot import name 'Interval' from 'solution' (/data/sandeep/leetcode-master/.verifaiws/253_Meeting_Rooms_II/solution.py)
=========================== short test summary info ============================
ERROR 253_Meeting_Rooms_II/test_253_Meeting_Rooms_II.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.04s ===============================
