============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0
rootdir: /data/sandeep/leetcode-master/.verifaiws
collected 4 items

1064_Fixed_Point/test_1064_Fixed_Point.py F..F                           [100%]

=================================== FAILURES ===================================
_______________________________ test_fixedPoint ________________________________

    def test_fixedPoint():
        s = Solution()
        assert s.fixedPoint([0, 2, 3, 4, 5, 6, 7, 8]) == 0
        assert s.fixedPoint([-10, -5, 0, 3, 7]) == 3
>       assert s.fixedPoint([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) == 0
E       assert 4 == 0
E        +  where 4 = <bound method Solution.fixedPoint of <solution.Solution object at 0x7f16532f0730>>([0, 1, 2, 3, 4, 5, ...])
E        +    where <bound method Solution.fixedPoint of <solution.Solution object at 0x7f16532f0730>> = <solution.Solution object at 0x7f16532f0730>.fixedPoint

1064_Fixed_Point/test_1064_Fixed_Point.py:8: AssertionError
__________________________ test_fixedPoint_duplicates __________________________

    def test_fixedPoint_duplicates():
        s = Solution()
>       assert s.fixedPoint([0, 1, 1, 3, 4]) == 1
E       assert 3 == 1
E        +  where 3 = <bound method Solution.fixedPoint of <solution.Solution object at 0x7f16532f3b80>>([0, 1, 1, 3, 4])
E        +    where <bound method Solution.fixedPoint of <solution.Solution object at 0x7f16532f3b80>> = <solution.Solution object at 0x7f16532f3b80>.fixedPoint

1064_Fixed_Point/test_1064_Fixed_Point.py:24: AssertionError
=========================== short test summary info ============================
FAILED 1064_Fixed_Point/test_1064_Fixed_Point.py::test_fixedPoint - assert 4 ...
FAILED 1064_Fixed_Point/test_1064_Fixed_Point.py::test_fixedPoint_duplicates
========================= 2 failed, 2 passed in 0.01s ==========================
